name: Upload to Tencent COS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Upload files to COS
      env:
        COS_BUCKET: ${{ secrets.COS_BUCKET }} # webstatic-1252276051
        COS_REGION: ${{ secrets.COS_REGION }} # ap-shanghai
        COS_UPLOAD_PATH: ${{ secrets.COS_UPLOAD_PATH }} # blog.wj2015.com
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
      run: |
        npm install -g cos-nodejs-sdk-v5
        node -e "
          const COS = require('cos-nodejs-sdk-v5');
          const fs = require('fs');
          const path = require('path');
          const cos = new COS({
            SecretId: process.env.TENCENT_SECRET_ID,
            SecretKey: process.env.TENCENT_SECRET_KEY,
          });
          const uploadDir = (dir, bucket, region, prefix) => {
            fs.readdirSync(dir).forEach(file => {
              const filePath = path.join(dir, file);
              cos.putObject({
                Bucket: bucket,
                Region: region,
                Key: \`\${prefix}/\${file}\`,
                Body: fs.readFileSync(filePath)
              }, (err, data) => {
                if (err) console.error(err);
                else console.log(\`Uploaded: \${file}\`);
              });
            });
          };
          uploadDir('public', process.env.COS_BUCKET, process.env.COS_REGION, process.env.COS_UPLOAD_PATH);
        "
